OBJ = main.o connect.o escape.o view.o hero.o flyer.o move.o spectator.o
EXE = a5
CC = gcc -Wall 

$(EXE):	$(OBJ)
	$(CC) -o $(EXE) $(OBJ)

main.o:	main.c defs.h
	$(CC) -c main.c

connect.o:	connect.c defs.h
	$(CC) -c connect.c

escape.o:	escape.c defs.h
	$(CC) -c escape.c

view.o:	view.c defs.h
	$(CC) -c view.c

hero.o:	hero.c defs.h
	$(CC) -c hero.c

flyer.o:	flyer.c defs.h
	$(CC) -c flyer.c

move.o:	move.c defs.h
	$(CC) -c move.c
	
spectator.o:	spectator.c defs.h
	$(CC) -c spectator.c

clean:
	rm -f $(EXE) $(OBJ)
